apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: hdfs
spec:
  containers:
  - image: gcr.io/google_containers/busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: container1
  restartPolicy: Always