kind: Service
apiVersion: v1
metadata:
  labels:
    nodetype: namenode
  name: namenode-service
  namespace: hdfs
spec:
  clusterIP: None
  selector:
    nodetype: namenode
  ports:
    - name: ipc
      protocol: TCP
      port: 8020
    - name: http
      protocol: TCP
      port: 50070
    - name: https
      protocol: TCP
      port: 50470
---
apiVersion: v1
kind: Pod
metadata:
  name: master
  namespace: hdfs
  labels:
    nodetype: namenode
  annotations:
    pod.beta.kubernetes.io/init-containers: '[
        {
            "name": "format-node",
            "image": "anupambasak/docker-hadoop",
            "command": [
              "/opt/hadoop-2.7.3/bin/hdfs",
              "--config",
              "/etc/hadoop",
              "namenode",
              "-format",
              "-force",
              "-nonInteractive",
              "-clusterid",
              "testcluster"
            ],
            "volumeMounts": [
                {
                    "name": "hdfs-config-vol",
                    "mountPath": "/etc/hadoop"
                },
                {
                  "name": "hdfs-namenode-vol",
                  "mountPath": "/data"
                }
            ]
        }
    ]'
spec:
  containers:
  - image: anupambasak/docker-hadoop
    command:
      - /opt/hadoop-2.7.3/bin/hdfs
      - "--config"
      - "/etc/hadoop"
      - "namenode"
    imagePullPolicy: IfNotPresent
    name: namenode
    volumeMounts:
    - name: hdfs-config-vol
      mountPath: /etc/hadoop
    - name: hdfs-namenode-vol
      mountPath: /data
  volumes:
  - name: hdfs-config-vol
    configMap:
      name: hdfs-config
  - name: hdfs-namenode-vol
    persistentVolumeClaim:
      claimName: hdfs-claim
  restartPolicy: Always

