apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdfs-volume
  namespace: hdfs
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: local-disk
  hostPath:
    path: /Users/anupam/git/kubernates/data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hdfs-claim
  namespace: hdfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-disk
  resources:
    requests:
      storage: 1Gi