apiVersion: v1
kind: ConfigMap
metadata:
  namespace: hdfs
  name: hdfs-config
data:
  core-site.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
        <property>
            <name>fs.defaultFS</name>
            <value>hdfs://localhost:9000</value>
        </property>
    </configuration>
